<h1 style="text-align: center">EXAMEN SEGUNDO BIMESTRE</h1>

In [123]:
import pandas as pd
import numpy as np
from io import StringIO 

<h3>1) Crea un Dataframe de 10 registros y 6 columnas y consigue las 5 primeros y los 5 ultimos registros</h3>

In [124]:
df = pd.DataFrame(np.random.randint(0,100,size=(10, 6)), columns=list('123456'))

print("PRIMEROS 5")
print(df.head(5))

print("ÚLTIMOS 5")
print(df.tail(5))


PRIMEROS 5
    1   2   3   4   5   6
0  41  95   8  30  99  96
1  32   7  90  42  59  16
2  44  15  24  22  33  31
3  40   2  74  54  85  52
4  91  92  71  89  30  48
ÚLTIMOS 5
    1   2   3   4   5   6
5  26  38  49   7   8  56
6  54  22  20  55  41  74
7  48  40  49  41  60  25
8  55  21  31  43  60  92
9  63  49  32  91  71  85


<h3>2) Crear un dataframe pasando un arreglo de numpy de 6 x 4 con una fecha como indice y con columnas A, B, C, D randomico</h3>

In [125]:
indices = ["2013-01-01",
          "2013-01-02",
          "2013-01-03",
          "2013-01-04",
          "2013-01-05",
          "2013-01-06"]

df = pd.DataFrame(np.random.rand(24).reshape(6,4), columns=list('ABCD'), index = indices)
print(df)

                   A         B         C         D
2013-01-01  0.214375  0.364168  0.387913  0.747001
2013-01-02  0.540255  0.066327  0.509146  0.573819
2013-01-03  0.967697  0.568633  0.981920  0.449675
2013-01-04  0.870724  0.861575  0.504578  0.645288
2013-01-05  0.266496  0.403864  0.824286  0.255879
2013-01-06  0.805182  0.713140  0.362472  0.095519


<h3>4) Crear un Dataframe con 10 registros y 6 columnas y con una propiedad del Dataframe mostrar las columnas, con otro comando mostrar los valores.</h3>


In [137]:
df = pd.DataFrame(np.random.randint(0,100,size=(10, 6)), columns=list('123456'))

print("COLUMNAS")
print(df.columns)

print("VALORES")
print(df.values)

COLUMNAS
Index(['1', '2', '3', '4', '5', '6'], dtype='object')
VALORES
[[35 91 33 43 78  1]
 [23 79 13  4 92 35]
 [73 93 29 32 11 60]
 [15 46 60 31 94 52]
 [98 21 91 53 77 23]
 [90 59 41  8 77 54]
 [59 63  6  1 17 67]
 [65  5 72 12 17 29]
 [79 95 30 84 63 83]
 [99 38 14 24 60 71]]


<h3>5) Crear un Dataframe con 10 registros y 6 columnas y con una funcion del Dataframe describir estadisticamente el Dataframe</h3>


In [127]:
df = pd.DataFrame(np.random.randint(0,100,size=(10, 6)), columns=list('123456'))

print("DESCRIPCIÓN ESTADÍSTICA")
print(df.describe())

DESCRIPCIÓN ESTADÍSTICA
               1          2          3          4          5          6
count  10.000000  10.000000  10.000000  10.000000  10.000000  10.000000
mean   49.500000  27.500000  43.200000  47.100000  63.600000  35.300000
std    35.951356  33.556751  27.871929  29.103074  25.721586  25.828709
min     1.000000   1.000000   8.000000   2.000000  30.000000   3.000000
25%    17.750000   2.500000  23.250000  33.250000  45.250000  13.250000
50%    48.500000   8.000000  36.000000  54.000000  64.000000  29.500000
75%    85.000000  42.500000  63.250000  55.750000  85.750000  54.750000
max    90.000000  89.000000  84.000000  97.000000  98.000000  77.000000


<h3>6) Crear un Dataframe con 10 registros y 6 columnas y con una funcion del Dataframe transponer los datos</h3>


In [128]:
df = pd.DataFrame(np.random.randint(0,100,size=(10, 6)), columns=list('123456'))

print("DATAFRAME TRANSPUESTO")
print(df.T)

DATAFRAME TRANSPUESTO
    0   1   2   3   4   5   6   7   8   9
1  92  40  61  53   5  80  82  55  32  48
2  44  10  96  67  56  67  25   2  23  55
3  48  66  55  28  85  59   8  93  86  25
4  53  60  46  50  23  47  93  36  27  70
5  31  27   9  40   8  56  93  58  98  18
6  45  28  20  95  94  81  25  97  13  94


<h3>7) Crear un Dataframe con 10 registros y 6 columnas y Ordenar el dataframe 1 vez por cada columna, ascendente y descendente</h3>

In [129]:
df = pd.DataFrame(np.random.randint(0,100,size=(10, 6)), columns=list('123456'))

df = pd.DataFrame(np.sort(df.values, axis=0), index=df.index, columns=df.columns)
print("ASCENDING")
print(df)

df = pd.DataFrame(-np.sort(-df.values, axis=0), index=df.index, columns=df.columns)
print("DESCENDING")
print(df)

ASCENDING
    1   2   3   4   5   6
0   6   3  11  22   1   0
1   9  12  19  33   7   3
2  17  21  40  33  10   6
3  19  33  43  34  13  15
4  20  34  43  36  38  32
5  30  42  63  51  54  40
6  40  49  70  68  60  54
7  69  52  85  73  73  57
8  90  73  90  79  74  70
9  96  74  94  99  96  87
DESCENDING
    1   2   3   4   5   6
0  96  74  94  99  96  87
1  90  73  90  79  74  70
2  69  52  85  73  73  57
3  40  49  70  68  60  54
4  30  42  63  51  54  40
5  20  34  43  36  38  32
6  19  33  43  34  13  15
7  17  21  40  33  10   6
8   9  12  19  33   7   3
9   6   3  11  22   1   0


<h3>8) Crear un Dataframe con 10 registros y 6 columnas llenas de números randomicos del 1 al 10 y seleccionar en un nuevo Dataframe solo los valores mayores a 7</h3>

In [130]:
df = pd.DataFrame(np.random.randint(1,11,size=(10, 6)), columns=list('123456'))
print(df)
print()

rslt_df = df[df > 7] 
print(rslt_df)

   1  2   3   4   5  6
0  4  9   7  10   7  6
1  4  5   1   4   7  7
2  4  8   3   7   8  4
3  5  5  10  10   1  6
4  6  1   7   6   8  7
5  7  6   7   7  10  2
6  8  3   6   6  10  3
7  1  3   1   9   1  9
8  4  1   8   4   4  7
9  8  7   6   8   6  7

     1    2     3     4     5    6
0  NaN  9.0   NaN  10.0   NaN  NaN
1  NaN  NaN   NaN   NaN   NaN  NaN
2  NaN  8.0   NaN   NaN   8.0  NaN
3  NaN  NaN  10.0  10.0   NaN  NaN
4  NaN  NaN   NaN   NaN   8.0  NaN
5  NaN  NaN   NaN   NaN  10.0  NaN
6  8.0  NaN   NaN   NaN  10.0  NaN
7  NaN  NaN   NaN   9.0   NaN  9.0
8  NaN  NaN   8.0   NaN   NaN  NaN
9  8.0  NaN   NaN   8.0   NaN  NaN


<h3>9) Crear un Dataframe con 10 registros y 6 columnas llenas de números randomicos del 1 al 10 o valores NaN. Luego llenar los valores NaN con 0.</h3>

In [131]:
df = pd.DataFrame(np.random.randint(1,11,size=(10, 6)), columns=list('123456'))
df = df[df > 4] 
print("DATAFRAME CON VALORES NAN")
print(df)
print("DATAFRAME SIN VALORES NAN")
print(df.fillna(0))

DATAFRAME CON VALORES NAN
     1     2     3     4     5     6
0  NaN   8.0   NaN   NaN   8.0   9.0
1  NaN  10.0   NaN   6.0   NaN   6.0
2  8.0   NaN   7.0   7.0   6.0   NaN
3  NaN   6.0   7.0   8.0   5.0   NaN
4  NaN   NaN   NaN   NaN   5.0   7.0
5  7.0   7.0  10.0   5.0   NaN   6.0
6  5.0   NaN   7.0  10.0   NaN   5.0
7  8.0   NaN   6.0   5.0   7.0   7.0
8  7.0   NaN   8.0  10.0   9.0   8.0
9  8.0   6.0   NaN   NaN  10.0  10.0
DATAFRAME SIN VALORES NAN
     1     2     3     4     5     6
0  0.0   8.0   0.0   0.0   8.0   9.0
1  0.0  10.0   0.0   6.0   0.0   6.0
2  8.0   0.0   7.0   7.0   6.0   0.0
3  0.0   6.0   7.0   8.0   5.0   0.0
4  0.0   0.0   0.0   0.0   5.0   7.0
5  7.0   7.0  10.0   5.0   0.0   6.0
6  5.0   0.0   7.0  10.0   0.0   5.0
7  8.0   0.0   6.0   5.0   7.0   7.0
8  7.0   0.0   8.0  10.0   9.0   8.0
9  8.0   6.0   0.0   0.0  10.0  10.0


<h3>10) Crear un Dataframe con 10 registros y 6 columnas llenas de números randomicos del 1 al 10 y sacar la media, la mediana, el promedio</h3>

In [132]:
df = pd.DataFrame(np.random.randint(1,11,size=(10, 6)), columns=list('123456'))
print("MEDIA")
print(df.mean())

print("MEDIANA")
print(df.median())

MEDIA
1    5.6
2    7.0
3    5.2
4    6.1
5    5.4
6    5.5
dtype: float64
MEDIANA
1    5.5
2    7.5
3    5.5
4    6.5
5    5.0
6    5.0
dtype: float64


<h3>11) Crear un Dataframe con 10 registros y 6 columnas llenas de números randomicos del 1 al 10, luego crear otro dateframe con 10 registros y 6 columnas llenas de números randomicos del 1 al 10 y anadirlo al primer Dataframe</h3>

In [133]:
df_1 = pd.DataFrame(np.random.randint(1,11,size=(10, 6)), columns=list('123456'))
df_2 = pd.DataFrame(np.random.randint(1,11,size=(10, 6)), columns=list('123456'))

print("PRIMER DATAFRAME")
print(df_1)

print("SEGUNDO DATAFRAME")
print(df_2)

print("DATAFRAME UNIDO")
print(df_1.append(df_2)) 

PRIMER DATAFRAME
    1  2   3  4  5   6
0   7  9   2  5  4   2
1  10  5   2  5  5   2
2   2  3   3  8  5   1
3   4  4   9  8  1   1
4   1  1   8  9  6  10
5   7  8   8  2  1   2
6   6  6   6  6  4   3
7   4  2  10  1  2   5
8   4  3   2  5  8   6
9  10  7   5  7  2   5
SEGUNDO DATAFRAME
    1  2  3   4  5   6
0   2  4  1  10  8   7
1   1  7  4   2  8   7
2   7  6  1   5  9   1
3   7  6  6   2  2   7
4   3  1  7  10  6   1
5   3  1  6   9  3   9
6   9  7  9   4  6   5
7  10  5  6   3  2   9
8   4  4  4   8  5   2
9  10  1  5   2  4  10
DATAFRAME UNIDO
    1  2   3   4  5   6
0   7  9   2   5  4   2
1  10  5   2   5  5   2
2   2  3   3   8  5   1
3   4  4   9   8  1   1
4   1  1   8   9  6  10
5   7  8   8   2  1   2
6   6  6   6   6  4   3
7   4  2  10   1  2   5
8   4  3   2   5  8   6
9  10  7   5   7  2   5
0   2  4   1  10  8   7
1   1  7   4   2  8   7
2   7  6   1   5  9   1
3   7  6   6   2  2   7
4   3  1   7  10  6   1
5   3  1   6   9  3   9
6   9  7   9   4  6   5
7  10  5   

<h3>12) Crear un Dataframe con 10 registros y 6 columnas llenas de strings. Luego, unir la columna 1 y 2 en una sola, la 3 y 4, y la 5 y 6 concatenando su texto.</h3>

In [134]:
data_string = """1,2,3,4,5,6
aa,ba,ca,da,ea,fa
ab,bb,cb,db,eb,fb
ac,bc,cc,dc,ec,fc
ad,bd,cd,dd,ed,fd
ae,be,ce,de,ee,fe
af,bf,cf,df,ef,ff
ag,bg,cg,dg,eg,fg
ah,bh,ch,dh,eh,fh
ai,bi,ci,di,ei,fi
aj,bj,cj,dj,ej,fj
                 """

data = StringIO(data_string)
df = pd.read_csv(data, sep=",")

cols = ["1", "2"]
df['1_2'] = df[cols].apply(lambda row: '-'.join(row.values.astype(str)), axis=1)

cols = ["3", "4"]
df['3_4'] = df[cols].apply(lambda row: '-'.join(row.values.astype(str)), axis=1)

cols = ["5", "6"]
df['5_6'] = df[cols].apply(lambda row: '-'.join(row.values.astype(str)), axis=1)

print("DATAFRAME CON COLUMNAS CONCATENADAS")
print(df[["1_2","3_4","5_6"]])

DATAFRAME CON COLUMNAS CONCATENADAS
     1_2    3_4    5_6
0  aa-ba  ca-da  ea-fa
1  ab-bb  cb-db  eb-fb
2  ac-bc  cc-dc  ec-fc
3  ad-bd  cd-dd  ed-fd
4  ae-be  ce-de  ee-fe
5  af-bf  cf-df  ef-ff
6  ag-bg  cg-dg  eg-fg
7  ah-bh  ch-dh  eh-fh
8  ai-bi  ci-di  ei-fi
9  aj-bj  cj-dj  ej-fj


<h3>13) Crear un Dataframe con 10 registros y 6 columnas llenas de números randomicos del 1 al 10 enteros, obtener la frecuencia de repeticion de los numeros enteros en cada columna</h3>

In [135]:
df = pd.DataFrame(np.random.randint(1,11,size=(10, 6)), columns=list('123456'))
print("DATAFRAME")
print(df)

for x in range(1,6):
    print("COLUMNA " + str(x))
    print(df[str(x)].value_counts())

DATAFRAME
   1  2   3   4   5   6
0  8  8   9  10   9   4
1  1  3   7   9   3   8
2  6  8   2   5   9   9
3  6  4   9  10   8   3
4  5  8   6   2   8   7
5  8  2   3  10   1   4
6  5  3   3   3   8   2
7  1  4   4   8   5   4
8  8  6  10   5   5  10
9  9  9   4   4  10   3
COLUMNA 1
8    3
6    2
5    2
1    2
9    1
Name: 1, dtype: int64
COLUMNA 2
8    3
4    2
3    2
9    1
6    1
2    1
Name: 2, dtype: int64
COLUMNA 3
9     2
4     2
3     2
10    1
7     1
6     1
2     1
Name: 3, dtype: int64
COLUMNA 4
10    3
5     2
9     1
8     1
4     1
3     1
2     1
Name: 4, dtype: int64
COLUMNA 5
8     3
9     2
5     2
10    1
3     1
1     1
Name: 5, dtype: int64


<h3>14) Crear un Dataframe con 10 registros y 3 columnas, A B C, llenas de números randomicos del 1 al 10 enteros. Crear una nueva columna con el calculo por fila (A * B ) / C</h3>

In [136]:
df = pd.DataFrame(np.random.randint(1,11,size=(10, 3)), columns=list('ABC'))
print("DATAFRAME")
print(df)

cols = ["A", "B", "C"]
df['CALCULO'] = df[cols].apply(lambda row: int(row["A"]) * int(row["B"]) / int(row["C"]), axis=1)

print("DATAFRAME CON COLUMNA CALCULO")
print(df)

DATAFRAME
    A   B  C
0   7   2  9
1   8   4  5
2   3   1  9
3   9   7  8
4   7   8  8
5   6   9  4
6   2  10  7
7   1   9  5
8   7   6  1
9  10   4  8
DATAFRAME CON COLUMNA CALCULO
    A   B  C    CALCULO
0   7   2  9   1.555556
1   8   4  5   6.400000
2   3   1  9   0.333333
3   9   7  8   7.875000
4   7   8  8   7.000000
5   6   9  4  13.500000
6   2  10  7   2.857143
7   1   9  5   1.800000
8   7   6  1  42.000000
9  10   4  8   5.000000
