# EXAMEN

In [178]:
import numpy as np
import pandas as pd
import scipy.ndimage
from scipy import misc

## 2) Crear un vector de ceros de tamaño 10

In [9]:
array_ceros = np.zeros(10)
print(array_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 3) Crear un vector de ceros de tamaño 10 y el de la posicion 5 sea igual a 1

In [15]:
array_ceros_con_uno = np.zeros(10)
array_ceros_con_uno[5] = 1
print(array_ceros_con_uno)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


## 4) Cambiar el orden de un vector de 50 elementos, el de la posicion 1 es el de la 50 etc.

In [20]:
array_50_elementos = np.arange(50)
array_50_elementos_al_reves = array_50_elementos[::-1]
print(array_50_elementos_al_reves)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


## 5) Crear una matriz de 3 x 3 con valores del cero al 8

In [23]:
matriz3x3 = np.arange(9).reshape(3,3)
print(matriz3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 6) Encontrar los indices que no sean cero en un arreglo

In [52]:
array_con_ceros =np.random.randint(3, size=10)
print("array_con_ceros", array_con_ceros)
bolean_array_con_ceros = array_con_ceros!=0
print("array_sin_ceros", bolean_array_con_ceros)
for i in range(len(array_con_ceros)):
    if bolean_array_con_ceros[i]:
        print("indice", i)


array_con_ceros [2 2 1 1 1 1 0 2 2 1]
array_sin_ceros [ True  True  True  True  True  True False  True  True  True]
indice 0
indice 1
indice 2
indice 3
indice 4
indice 5
indice 7
indice 8
indice 9


## 7) Crear una matriz de identidad 3 x 3 

In [54]:
matriz3x3_identidad = np.eye(3)
print(matriz3x3_identidad)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 8) Crear una matriz 3 x 3 x 3 con valores randomicos

In [60]:
matriz3x3x3 =np.random.randint(10, size=27).reshape(3,3,3)
print(matriz3x3x3)

[[[7 2 1]
  [0 8 8]
  [1 9 4]]

 [[7 2 8]
  [9 3 4]
  [7 4 0]]

 [[3 9 7]
  [7 4 0]
  [6 5 5]]]


## 10) Sacar los colores RGB unicos en una imagen (cuales rgb existen ej: 0, 0, 0 - 255,255,255 -> 2 colores)

In [179]:
mapache = misc.face()

## 11) ¿Como crear una serie de una lista, diccionario o arreglo?

In [67]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
serie_lista = pd.Series(mylist)
serie_tupla = pd.Series(myarr)
serie_diccionario = pd.Series(mydict)
print(serie_lista)
print(serie_tupla)
print(serie_diccionario)

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int32
a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64


## 12) ¿Como convertir el indice de una serie en una columna de un DataFrame?

In [76]:
ser = pd.Series(mydict) 
df1 = pd.DataFrame(ser)
df1["columna_indice"] = df1.index
print(df1)

    0 columna_indice
a   0              a
b   1              b
c   2              c
e   3              e
d   4              d
f   5              f
g   6              g
h   7              h
i   8              i
j   9              j
k  10              k
l  11              l
m  12              m
n  13              n
o  14              o
p  15              p
q  16              q
r  17              r
s  18              s
t  19              t
u  20              u
v  21              v
w  22              w
x  23              x
y  24              y
z  25              z


## 13) ¿Como combinar varias series para hacer un DataFrame?

In [89]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

df_combinado = pd.DataFrame(dict(ser1 = ser1, ser2 = ser2))

print(df_combinado)

   ser1  ser2
0     a     0
1     b     1
2     c     2
3     e     3
4     d     4
5     f     5
6     g     6
7     h     7
8     i     8
9     j     9
10    k    10
11    l    11
12    m    12
13    n    13
14    o    14
15    p    15
16    q    16
17    r    17
18    s    18
19    t    19
20    u    20
21    v    21
22    w    22
23    x    23
24    y    24
25    z    25


## 14) ¿Como obtener los items que esten en una serie A y no en una serie B?

In [102]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
main_list = np.setdiff1d(ser1,ser2)
print(main_list)

[1 2 3]


## 15) ¿Como obtener los items que no son comunes en una serie A y serie B?

In [108]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
main_list1 = np.setdiff1d(ser1,ser2)
main_list2 = np.setdiff1d(ser2,ser1)
main_concat = np.concatenate((main_list1, main_list2), axis=0)
print(main_concat)

[1 2 3 6 7 8]


## 16) ¿Como obtener el numero de veces que se repite un valor en una serie?

In [119]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
ser.groupby(ser).size()

a    4
b    3
c    4
d    4
e    2
f    3
g    6
h    4
dtype: int64

## 17) ¿Como mantener los 2 valores mas repetidos de una serie, y a los demas valores cambiarles por 0 ?

In [151]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
print(ser)
max_values = ser.groupby(ser).size().sort_values(ascending=False)[:2].to_numpy()
print("max",max_values)
for x in range(len(ser)):
    if (ser[x] in max_values):
        ser[x] = 0
        
print(ser)

0     1
1     3
2     3
3     2
4     2
5     1
6     4
7     1
8     3
9     3
10    4
11    2
dtype: int32
max [4 3]
0     1
1     0
2     0
3     2
4     2
5     1
6     0
7     1
8     0
9     0
10    0
11    2
dtype: int32


## 18) ¿Como transformar una serie de un arreglo de numpy a un DataFrame con un `shape` definido?

In [163]:
ser = pd.Series(np.random.randint(1, 10, 35)).to_numpy().reshape(7,5)
print(ser)
print(pd.DataFrame(ser))


[[3 6 7 2 6]
 [5 9 6 1 7]
 [8 4 9 5 3]
 [1 8 8 9 1]
 [4 6 8 3 9]
 [2 1 5 2 6]
 [8 9 8 6 2]]
   0  1  2  3  4
0  3  6  7  2  6
1  5  9  6  1  7
2  8  4  9  5  3
3  1  8  8  9  1
4  4  6  8  3  9
5  2  1  5  2  6
6  8  9  8  6  2


## 19) ¿Obtener los valores de una serie conociendo la posicion por indice?

In [165]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
# a e i o u

for x in range(len(ser)):
    if x in pos:
        print(ser[x])

a
e
i
o
u


## 20) ¿Como anadir series vertical u horizontalmente a un DataFrame?

In [173]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
print(pd.concat([ser1, ser2], axis= 1))


   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


## 21)¿Obtener la media de una serie agrupada por otra serie?

## 22)¿Como importar solo columnas especificas de un archivo csv?


In [177]:
path = "https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv"
columnas = ["crim", "zn"]
df2 = pd.read_csv(
    path,
    nrows=10,
    usecols = columnas)
print(df2)

      crim    zn
0  0.00632  18.0
1  0.02731   0.0
2  0.02729   0.0
3  0.03237   0.0
4  0.06905   0.0
5  0.02985   0.0
6  0.08829  12.5
7  0.14455  12.5
8  0.21124  12.5
9  0.17004  12.5
