# NUMPY

In [2]:
import numpy as np

In [10]:
print(type([1,2,3]))
print(type((1,2,3)))
print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


## np.zeros()

In [5]:
np.zeros(5) #1 solo número para un arreglo
np.zeros([5,5]) #1 lista o tupla para una matriz de n dimensiones
np.zeros([2,2,2,2,2])
np.zeros([1000,200])

(2, 2, 2, 2, 2)

## np.ones()

In [21]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

## np.eye() Matriz identidad

In [23]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## np.arange()

In [25]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [28]:
np.arange(5,10) # [5,10[

array([5, 6, 7, 8, 9])

In [30]:
np.arange(-12,1) #[-12,1[

array([-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [31]:
np.arange(0,20,2) #Del [-0,20[ en intervalos de 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
np.arange(0,2.1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

## reshape() para cambiar las dimensiones de un arreglo de numpy

In [36]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [40]:
np.zeros(20).reshape(2,5,2).reshape(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

## shape Longitud de un arreglo

In [41]:
len(np.ones(12))

12

In [45]:
len(np.ones(12).reshape(4,3))

4

In [49]:
np.ones(12).reshape(2,2,3).shape

(2, 2, 3)

In [51]:
np.array([1,7,12,16]).reshape(2,2)

array([[ 1,  7],
       [12, 16]])

In [59]:
a = np.array([10,10,10])
b = np.array([5,5,5])

## Operaciones

In [61]:
# suma
a+b

array([15, 15, 15])

In [62]:
# resta
a-b

array([5, 5, 5])

In [63]:
a + 7

array([17, 17, 17])

In [64]:
a - 8

array([2, 2, 2])

In [65]:
#Multiplicacion
a * b

array([50, 50, 50])

In [66]:
#Division
a/2

array([5., 5., 5.])

In [69]:
#Modulo
a % b

array([0, 0, 0], dtype=int32)

In [70]:
a % 3

array([1, 1, 1], dtype=int32)

In [71]:
muestra = np.arange(20).reshape(5,2,2)

In [72]:
muestra

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [73]:
respuesta_glucosa = muestra > 5

In [74]:
respuesta_glucosa

array([[[False, False],
        [False, False]],

       [[False, False],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

In [79]:
muestra[muestra%2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [78]:
muestra[respuesta_glucosa]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

### Mayores a 5, menores a 14 y que sean pares

In [95]:
sub_muestra = muestra[muestra>5]

In [96]:
sub_muestra = sub_muestra[sub_muestra<14]

In [97]:
sub_muestra = sub_muestra[sub_muestra%2==0]

In [98]:
sub_muestrab

array([ 6,  8, 10, 12, 14, 16, 18])

In [156]:
muestra[(muestra>5) & (muestra<14) & (muestra%2==0)]

array([ 6,  8, 10, 12])

### dot() producto punto

In [5]:
A = np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [7]:
B = np.arange(4, 8).reshape(2,2)
B

array([[4, 5],
       [6, 7]])

In [8]:
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [9]:
B.dot(A)

array([[10, 19],
       [14, 27]])

In [10]:
np.dot(A,B)

array([[ 6,  7],
       [26, 31]])

In [11]:
np.dot(B,A)

array([[10, 19],
       [14, 27]])

### sum()

In [13]:
arreglo_doce = np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
arreglo_doce.sum()

66

### min() y max() 

In [21]:
arreglo_doce.max()

11

In [22]:
arreglo_doce.min()

0

In [24]:
arreglo_doce[3:9].max()

8

In [25]:
arreglo_doce.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [26]:
arreglo_doce.sum()

66

### sum(axis=eje)

In [30]:
arreglo_doce.reshape(3,2,2).sum(axis = 0)

array([[12, 15],
       [18, 21]])

In [31]:
arreglo_doce.reshape(3,2,2).sum(axis = 1)

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [32]:
arreglo_doce.reshape(3,2,2).sum(axis = 2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])