In [1]:
import numpy as np

### Radianes

In [6]:
arreglo_grados = np.array([0, 30, 25, 60, 90])
arreglo_grados

array([ 0, 30, 25, 60, 90])

In [7]:
arreglo_radianes = arreglo_grados * np.pi / 180
arreglo_radianes

array([0.        , 0.52359878, 0.43633231, 1.04719755, 1.57079633])

### Funciones trigonométricas


In [8]:
np.sin(arreglo_radianes)

array([0.        , 0.5       , 0.42261826, 0.8660254 , 1.        ])

In [9]:
np.cos(arreglo_radianes)

array([1.00000000e+00, 8.66025404e-01, 9.06307787e-01, 5.00000000e-01,
       6.12323400e-17])

In [10]:
np.tan(arreglo_radianes)

array([0.00000000e+00, 5.77350269e-01, 4.66307658e-01, 1.73205081e+00,
       1.63312394e+16])

### random

In [45]:
numero_random = np.random.randint(11) # [0,11[
numero_random

10

In [46]:
numero_random_negativo = np.random.randint(-9, 2) #[-9,2[
numero_random_negativo

-8

In [56]:
arreglo_random = np.random.randint(10, 20, 5)
arreglo_random

array([10, 19, 11, 18, 14])

In [51]:
np.random.rand(27).reshape(3,3,3)

array([[[0.12001821, 0.23801042, 0.19343852],
        [0.69397725, 0.09608426, 0.92625921],
        [0.06849592, 0.14919654, 0.15045257]],

       [[0.9780913 , 0.24858798, 0.395519  ],
        [0.90284322, 0.14610785, 0.23316423],
        [0.91700152, 0.32253997, 0.50480836]],

       [[0.93638936, 0.73615259, 0.4751294 ],
        [0.89368808, 0.61602323, 0.6192117 ],
        [0.19932629, 0.49574438, 0.6474045 ]]])

In [54]:
np.random.rand(3,3,3)

array([[[0.77895214, 0.78839425, 0.28432937],
        [0.09594701, 0.95701586, 0.02729416],
        [0.03747042, 0.02592105, 0.73250252]],

       [[0.60562924, 0.0168993 , 0.53213761],
        [0.98058307, 0.44740872, 0.40400391],
        [0.02063957, 0.00462386, 0.16370204]],

       [[0.40419645, 0.92042279, 0.38807655],
        [0.57955708, 0.49210485, 0.59017087],
        [0.06489298, 0.74038736, 0.90867426]]])

### average(), median(), etc

In [57]:
np.average(arreglo_random)

14.4

In [58]:
np.mean(arreglo_random)

14.4

In [59]:
np.median(arreglo_random)

14.0

In [60]:
np.std(arreglo_random)

3.6110940170535573

In [61]:
np.var(arreglo_random)

13.039999999999997

In [62]:
arreglo_random.mean()

14.4